import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'building',
  title: '建築作品',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'タイトル', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'titleEn', title: 'Title (English)', type: 'string' }),
    defineField({ name: 'description', title: '説明', type: 'text', validation: (Rule) => Rule.required() }),
    defineField({ name: 'descriptionEn', title: 'Description (English)', type: 'text' }),
    defineField({ name: 'year', title: '建造年', type: 'number', validation: (Rule) => Rule.min(1900).max(2100) }),
    defineField({ name: 'location', title: '所在地', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'locationEn', title: 'Location (English)', type: 'string' }),
    defineField({ name: 'region', title: '地域', type: 'string', options: { list: [
      { title: '北海道', value: 'hokkaido' }, { title: '東北', value: 'tohoku' },
      { title: '関東', value: 'kanto' }, { title: '中部', value: 'chubu' },
      { title: '近畿', value: 'kinki' }, { title: '中国', value: 'chugoku' },
      { title: '四国', value: 'shikoku' }, { title: '九州', value: 'kyushu' },
    ] } }),
    defineField({ name: 'regionEn', title: 'Region (English)', type: 'string' }),
    defineField({ name: 'status', title: '状態', type: 'string', options: { list: [{ title: '現存', value: '現存' }, { title: '現存せず', value: '現存せず' }] } }),
    defineField({ name: 'statusEn', title: 'Status (English)', type: 'string', options: { list: [{ title: 'Existing', value: 'Existing' }, { title: 'Demolished', value: 'Demolished' }] } }),
    defineField({ name: 'image', title: '画像', type: 'image' }),
    defineField({ name: 'lat', title: '緯度', type: 'number' }),
    defineField({ name: 'lng', title: '経度', type: 'number' }),
    defineField({ name: 'overview', title: '建築概観', type: 'text' }),
    defineField({ name: 'overviewEn', title: 'Overview (English)', type: 'text' }),
    defineField({ name: 'history', title: '歴史背景', type: 'text' }),
    defineField({ name: 'historyEn', title: 'History (English)', type: 'text' }),
    defineField({ name: 'significance', title: '建築価値と研究意義', type: 'text' }),
    defineField({ name: 'significanceEn', title: 'Significance (English)', type: 'text' }),
    defineField({ name: 'survey', title: '調査記録', type: 'text' }),
    defineField({ name: 'surveyEn', title: 'Survey (English)', type: 'text' }),
    defineField({ name: 'interview', title: 'インタビュー', type: 'text' }),
    defineField({ name: 'interviewEn', title: 'Interview (English)', type: 'text' }),
    defineField({ name: 'documentary', title: 'ドキュメンタリー', type: 'text' }),
    defineField({ name: 'documentaryEn', title: 'Documentary (English)', type: 'text' }),
    defineField({ name: 'archives', title: '档案資料', type: 'text' }),
    defineField({ name: 'archivesEn', title: 'Archives (English)', type: 'text' }),
    defineField({ name: 'relatedArticle', title: '関連記事', type: 'text' }),
    defineField({ name: 'relatedArticleEn', title: 'Related Articles (English)', type: 'text' }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'year' },
  },
})
